[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = ubstudioz.duckdns.org

[v3_req]
subjectAltName = DNS:ubstudioz.duckdns.org, DNS:localhost
